#!/usr/bin/env node
'use strict';

/* Downloads the latin subset of the two webfonts and writes a self-hosted
   fonts.css. Self-hosting keeps the page free of third-party runtime
   dependencies, matching the vendored Leaflet. */

const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const FONT_DIR = path.join(ROOT, 'src', 'fonts');
const CSS_OUT = path.join(ROOT, 'src', 'styles', 'fonts.css');

const GOOGLE_CSS =
  'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600&family=Inter:wght@400;600&display=swap';

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

function get(url, headers) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: headers || {} }, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          return resolve(get(res.headers.location, headers));
        }
        if (res.statusCode !== 200) return reject(new Error(`${res.statusCode} for ${url}`));
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => resolve(Buffer.concat(chunks)));
      })
      .on('error', reject);
  });
}

async function main() {
  fs.mkdirSync(FONT_DIR, { recursive: true });

  const css = (await get(GOOGLE_CSS, { 'User-Agent': UA })).toString('utf8');

  /* Google emits a `/* subset *\/` comment before each @font-face block. */
  const blocks = css.split('/*').slice(1);
  const kept = [];

  /* Google serves one variable font file per family, referenced by every
     weight. Key files by content hash so the same bytes ship once. */
  const byHash = new Map();

  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf('*/')).trim();
    if (subset !== 'latin') continue;

    const block = raw.slice(raw.indexOf('*/') + 2);
    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1];
    const style = (block.match(/font-style:\s*(\w+)/) || [])[1] || 'normal';
    const url = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    if (!family || !url) continue;

    const bytes = await get(url, { 'User-Agent': UA });
    const hash = crypto.createHash('sha256').update(bytes).digest('hex').slice(0, 8);

    let file = byHash.get(hash);
    if (!file) {
      file = `${family.toLowerCase()}-${hash}.woff2`;
      fs.writeFileSync(path.join(FONT_DIR, file), bytes);
      byHash.set(hash, file);
      process.stdout.write(`  ${file} (${Math.round(bytes.length / 1024)} KB)\n`);
    }

    kept.push(
      [
        '@font-face {',
        `  font-family: "${family}";`,
        `  font-style: ${style};`,
        `  font-weight: ${weight};`,
        '  font-display: swap;',
        `  src: url("../fonts/${file}") format("woff2");`,
        '  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,',
        '    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,',
        '    U+2212, U+2215, U+FEFF, U+FFFD;',
        '}',
      ].join('\n')
    );
  }

  if (!kept.length) throw new Error('no latin font faces found — Google CSS format may have changed');

  fs.writeFileSync(
    CSS_OUT,
    `/* Generated by scripts/fetch-fonts.js. Do not edit by hand. */\n\n${kept.join('\n\n')}\n`
  );
  console.log(`  wrote src/styles/fonts.css (${kept.length} faces)`);
}

main().catch((err) => {
  console.error(`\n  font fetch failed: ${err.message}\n`);
  process.exit(1);
});
